### ISSUE TITLE
유닛 등록 화면

### ISSUE THREAD

**Issue by Grandeun222** [datagurukr/Project_MathExam#18]
유닛설명, 부연설명

프론트에 어떤 UI로 표현할것인지 선 제안후 협의

**Comment by Grandeun222** [comment]
상세 수정 내역 작성 요

**Comment by Grandeun222** [comment]
1. 유닛설명 / 부연설명 등록하는 방법
2. 프론트에서 어떻게 구현되었는지

설명 좀 달아주세요.

**Comment by datagurukr** [comment]
참고 : https://drive.google.com/open?id=0B3gBryFKbG9HS201SDZFRlFVOHM
