### ISSUE TITLE
메인의 공지사항과 Q&A 영역을 통일하고 대제목 클릭 시 제목 리스트가 나오도록 > 제목 클릭 시 상세화면으로 이동.

### ISSUE THREAD

**Issue by Grandeun222** [datagurukr/Project_MathExam#24]

**Comment by datagurukr** [comment]
디자인수정 필요

**Comment by Grandeun222** [comment]
1. 공지사항 / Q&A 링크 처리 안됨.
2. 공지사항 / Q&A 리스트 순번 무조건 1. 으로 표기됨

**Comment by datagurukr** [comment]
공지사항 / Q&A 링크 처리 안됨. >> 더보기 버튼 추가함
공지사항 / Q&A 리스트 순번 무조건 1. 으로 표기됨 >> 1 ~ 5번 까지 나오도록 수정함
